export enum AuthModuleEnum {
    HOSPITAL = 'HOSPITAL',
    TRANSACTION = 'TRANSACTION',
    USER = 'USER',
    AUTHENTICATION = 'AUTHENTICATION',
    GLOBAL_SETTING = 'GLOBAL_SETTING',
    SERVICE_GROUP = 'SERVICE_GROUP',
    REVENUE_HEAD = 'REVENUE_HEAD',
    SERVICE = 'SERVICE'
}
