package com.james.medpay.core.constant;

public class AuthPermissions {
	// Authentication module
	// Page
	public static final String ACCESS_AUTH_PAGE_USER = "ACCESS_AUTH_PAGE_USER";
	public static final String ACCESS_AUTH_PAGE_ROLE = "ACCESS_AUTH_PAGE_ROLE";
	public static final String ACCESS_AUTH_PAGE_PERMISSION = "ACCESS_AUTH_PAGE_PERMISSION";
	// Action
	// user
	public static final String ACCESS_AUTH_ACTION_USER_ASSIGN_ROLE = "ACCESS_AUTH_ACTION_USER_ASSIGN_ROLE";
	// role
	public static final String ACCESS_AUTH_ACTION_ROLE_CREATE = "ACCESS_AUTH_ACTION_ROLE_CREATE";
	public static final String ACCESS_AUTH_ACTION_ROLE_UPDATE = "ACCESS_AUTH_ACTION_ROLE_UPDATE";
	public static final String ACCESS_AUTH_ACTION_ROLE_STATUS = "ACCESS_AUTH_ACTION_ROLE_STATUS";
	// permission
	public static final String ACCESS_AUTH_ACTION_PERMISSION_VIEW = "ACCESS_AUTH_ACTION_PERMISSION_VIEW";

	// Users module
	// Page
	public static final String ACCESS_USER_PAGE_VIEW = "ACCESS_USER_PAGE_VIEW";
	public static final String ACCESS_USER_PAGE_CREATE = "ACCESS_USER_PAGE_CREATE";
	public static final String ACCESS_USER_PAGE_REPORT = "ACCESS_USER_PAGE_REPORT";
	// Action
	public static final String ACCESS_USER_ACTION_VIEW = "ACCESS_USER_ACTION_VIEW";
	public static final String ACCESS_USER_ACTION_CREATE = "ACCESS_USER_ACTION_CREATE";
	public static final String ACCESS_USER_ACTION_UPDATE = "ACCESS_USER_ACTION_UPDATE";
	public static final String ACCESS_USER_ACTION_DOWNLOAD_REPORT = "ACCESS_USER_ACTION_DOWNLOAD_REPORT";

	// Transaction module
	public static final String ACCESS_TRANSACTION_PAGE_VIEW = "ACCESS_TRANSACTION_PAGE_VIEW";
	public static final String ACCESS_TRANSACTION_PAGE_PAYMENT_STATUS = "ACCESS_TRANSACTION_PAGE_VIEW_PAYMENT_STATUS";
	public static final String ACCESS_TRANSACTION_PAGE_PAYMENT_DETAILS = "ACCESS_TRANSACTION_PAGE_PAYMENT_DETAILS";
	public static final String ACCESS_TRANSACTION_PAGE_RECONCILE_PAYMENT = "ACCESS_TRANSACTION_PAGE_RECONCILE_PAYMENT";
	public static final String ACCESS_TRANSACTION_PAGE_REPRINT = "ACCESS_TRANSACTION_PAGE_REPRINT";
	public static final String ACCESS_TRANSACTION_PAGE_REPORT = "ACCESS_TRANSACTION_PAGE_REPORT";
	// Action
	public static final String ACCESS_TRANSACTION_ACTION_VIEW = "ACCESS_TRANSACTION_ACTION_VIEW";
	public static final String ACCESS_TRANSACTION_ACTION_CREATE = "ACCESS_TRANSACTION_ACTION_CREATE";
	public static final String ACCESS_TRANSACTION_ACTION_UPDATE = "ACCESS_TRANSACTION_ACTION_UPDATE";
	public static final String ACCESS_TRANSACTION_ACTION_DOWNLOAD_REPORT = "ACCESS_TRANSACTION_ACTION_DOWNLOAD_REPORT";

	// Hospital module
	//Page
	public static final String ACCESS_HOSPITAL_PAGE_VIEW = "ACCESS_HOSPITAL_PAGE_VIEW";
	public static final String ACCESS_HOSPITAL_PAGE_CREATE = "ACCESS_HOSPITAL_PAGE_CREATE";
	public static final String ACCESS_HOSPITAL_PAGE_CONFIGURE = "ACCESS_HOSPITAL_PAGE_CONFIGURE";
	// Action
	public static final String ACCESS_HOSPITAL_ACTION_VIEW = "ACCESS_HOSPITAL_ACTION_VIEW";
	public static final String ACCESS_HOSPITAL_ACTION_CREATE = "ACCESS_HOSPITAL_ACTION_CREATE";
	public static final String ACCESS_HOSPITAL_ACTION_UPDATE = "ACCESS_HOSPITAL_ACTION_UPDATE";
	public static final String ACCESS_HOSPITAL_ACTION_DOWNLOAD_REPORT = "ACCESS_HOSPITAL_ACTION_DOWNLOAD_REPORT";

	// Global Setting
	public static final String ACCESS_GLOBAL_SETTING_PAGE_HOSPITAL = "ACCESS_GLOBAL_SETTING_PAGE_HOSPITAL";
	public static final String ACCESS_GLOBAL_SETTING_PAGE_USER = "ACCESS_GLOBAL_SETTING_PAGE_USER";
	public static final String ACCESS_GLOBAL_SETTING_ROLE_PERMISSION = "ACCESS_GLOBAL_SETTING_ROLE_PERMISSION";
	public static final String ACCESS_GLOBAL_SETTING_TRANSACTION = "ACCESS_GLOBAL_SETTING_TRANSACTION";

	// Service Group
	public static final String ACCESS_SERVICE_GROUP_PAGE_CREATE = "ACCESS_SERVICE_GROUP_PAGE_CREATE";
	public static final String ACCESS_SERVICE_GROUP_PAGE_MANAGE = "ACCESS_SERVICE_GROUP_PAGE_MANAGE";

	// Revenue Head
	public static final String ACCESS_REVENUE_HEAD_PAGE_CREATE = "ACCESS_REVENUE_HEAD_PAGE_CREATE";
	public static final String ACCESS_REVENUE_HEAD_PAGE_MANAGE = "ACCESS_REVENUE_HEAD_PAGE_MANAGE";

	// Service
	public static final String ACCESS_SERVICE_PAGE_CREATE = "ACCESS_SERVICE_PAGE_CREATE";
	public static final String ACCESS_SERVICE_PAGE_MANAGE = "ACCESS_SERVICE_PAGE_MANAGE";

}
